example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
    
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_XML
from mywatchlist.views import show_json
from mywatchlist.views import show_movielink

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_movielink, name='show_movielink'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_XML, name='show_XML'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include ('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist 
from todolist.views import login_user 
from todolist.views import logout_user 
from todolist.views import create_task 
from todolist.views import register 
from todolist.views import register 
from todolist.views import show_json 
from todolist.views import add_task 


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('createtask/', create_task, name='create_task'),
    path('json/', show_json, name='show_json'),
    path('add/', add_task, name='add_task'),
]

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class BarangWatchlist(models.Model):
    watched = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    rating = models.TextField()
    release_date = models.IntegerField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length = 255)
    description = models.TextField()

todolist/forms.py
from django import forms
from todolist.models import Task

class taskform(forms.ModelForm):
    class Meta:
        model = Task
        fields = {"title", "description"}

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
# pengambilan data dari database
from django.shortcuts import render
from katalog.models import CatalogItem

# memanggil fungsi dan menyimpan hasil query ke database
# TODO: Create your views here.
def show_katalog(request):
    data_item_catalog = CatalogItem.objects.all()
    context = {
    'item_katalog': data_item_catalog,
}
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import BarangWatchlist
from django.http import HttpResponse
from django.core import serializers


# Create your views here.
def show_mywatchlist(request):
    data_barang_watchlist = BarangWatchlist.objects.all()
    context = {
        'movie_list': data_barang_watchlist,
        'nama': 'Audrey Zefanya Priyambodo',
        'Student ID': '2106650443'
    }
    return render(request, "mywatchlist.html", context)

def show_XML(request):
    data = BarangWatchlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWatchlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_movielink(request):
    data_barang_watchlist = BarangWatchlist.objects.all()
    context = {
        'movie_list': data_barang_watchlist,
        'nama': 'Audrey Zefanya Priyambodo',
        'Student ID': '2106650443'
    }
    return render(request, "movielink.html", context)

todolist/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.http import JsonResponse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from todolist.forms import taskform
from django.contrib import messages
from todolist.forms import taskform
from todolist.models import Task
from django.urls import reverse
import datetime
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = Task.objects.filter(user = request.user)
    context = {
        'list_todolist' : data_todolist,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, 'todolist.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sign up success!')
            return redirect('todolist:login_user')
        
    context = {'form':form}
    return render(request, 'register.html', context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == "POST":
        form = taskform(request.POST)
        form.instance.user = request.user
        form.instance.date = datetime.datetime.now()
        if form.is_valid():
            form.save()
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            return response
    else:
        form = taskform()
    return render(request, "createtask.html")

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login_user'))
    response.delete_cookie('last_login')
    return response

def show_json(request):
    data_todolist = Task.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data_todolist), content_type="application/json")

@csrf_exempt
def add_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task.objects.create(
            title = title, 
            description = description, 
            date = datetime.date.today(), 
            user = request.user)
        return JsonResponse(
            {
                "pk": task.pk,
                "fields": {
                    "title": task.title,
                    "description": task.description,
                    "date": task.date,
                },
            },
        )

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Audrey Zefanya Priyambodo</p>

  <h5>Student ID: </h5>
  <p>2106650443</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}

    {% for item in item_katalog %}
        <tr>
            <th>{{item.item_name}}</th>
            <th>{{item.item_price}}</th>
            <th>{{item.item_stock}}</th>
            <th>{{item.rating}}</th>
            <th>{{item.description}}</th>
            <th>{{item.item_url}}</th>
        </tr>
    {% endfor %}

  </table>

 {% endblock content %}

mywatchlist/templates/movielink.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Audrey Zefanya Priyambodo</p>

  <h5>Student ID: </h5>
  <p>2106650443</p>

  <a href="/mywatchlist/html">html</a>
  <a href="/mywatchlist/xml">xml</a>
  <a href="/mywatchlist/json">json</a>

  {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Audrey Zefanya Priyambodo</p>

  <h5>Student ID: </h5>
  <p>2106650443</p>

  <table>
    <tr>
      <th>Title</th>
      <th>Release Date</th>
      <th>Watched</th>
      <th>Rating</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}

    {% for item in movie_list %}
        <tr>
            <th>{{item.title}}</th>
            <th>{{item.release_date}}</th>
            <th>{{item.watched}}</th>
            <th>{{item.rating}}</th>
            <th>{{item.review}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/createtask.html
{% extends 'base.html' %}

{% block meta %}
<title>New Task</title>
{% endblock meta %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Hi, {{ user }}!</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todolist:show_todolist' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todolist:create_task' %}">Create Task</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:logout_user' %}">Logout</a>
            </li>
          </ul>

        </div>
      </nav>

    <style>
        *{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }
        body{
            background-image: url(https://cdn.dribbble.com/users/402090/screenshots/7972050/media/6dbbc85389e40707b39435357452fe27.gif);
        }
        .btn{
            border: none;
            outline: none;
            height: 40px;
            width: 50%;
            background-color: rgb(255, 150, 255);
            color: rgb(255, 255, 255);
            border-radius: 4px;
            font-weight: bold;
        }
        .btn:hover{
            background: rgb(148, 231, 186);
            border: 1px solid;
            color: white;
        }
    
    </style>

<div class = "createtask">

    <section class="Form my-5 mx-5">
        <div class="container">
                <div class="col-lg-6 px-5 pt-5">
                    <h1 class="font-weight-bold py-3">Create a New Task</h1>
                    <br>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Task</td>
                <td><input type="text" name="title" placeholder="Task keberapa?:)" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Description</td>
                <td><input type="text" name="description" placeholder="Description" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><br><br><input class="btn" type="submit" name="submit" value="Create"/></td>
            </tr>

        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>

    <style>
        *{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }
        body{
            background-image: url(https://cdn.dribbble.com/users/402090/screenshots/7972050/media/6dbbc85389e40707b39435357452fe27.gif);
        }
        .btn{
            border: none;
            outline: none;
            height: 50px;
            width: 100%;
            background-color: rgb(168, 235, 168);
            color: rgb(0, 0, 0);
            border-radius: 4px;
            font-weight: bold;
        }
        .btn:hover{
            background: rgb(117, 174, 236);
            border: 1px solid;
            color: rgb(0, 0, 0);
        }
    </style>

<div class = "login">
    
    <section class="Form my-5 mx-5">
        <div class="container">
                <div class="col-lg-6 px-5 pt-5">
                    <h1 class="font-weight-bold py-3">Hello,</h1>
                    <h4>please sign into your account</h4>
                    <br>

    <form method="POST" action="">
        {% csrf_token %}
            <tr>
                <td>Username</td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
            <br>
                    
            <tr>
                <td>Password</td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
            <br>

            <tr>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
            <br>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}		
        
    Didn't have an account? <a href="{% url 'todolist:register' %}">Sign up here!</a>
    <br>
    <br>
    <br>

</div>

{% endblock content %}
  </body>

</html>

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Sign Up Account</title>
{% endblock meta %}

{% block content %}  

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>

    <style>
        *{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }
        body{
            background-image: url(https://cdn.dribbble.com/users/402090/screenshots/7972050/media/6dbbc85389e40707b39435357452fe27.gif);
        }
        .btn{
            border: none;
            outline: none;
            height: 50px;
            width: 100%;
            background-color: rgb(253, 255, 148);
            color: black;
            border-radius: 4px;
            font-weight: bold;
        }
        .btn:hover{
            background: rgb(0, 0, 0);
            border: 1px solid;
            color: white;
        }
    </style>

<div class = "sign up">
    
    <section class="Form my-5 mx-5">
        <div class="container">
                <div class="col-lg-6 px-5 pt-5">
                    <h1 class="font-weight-bold py-3">Sign Up</h1>
                    <h4>Let's sign up your account here!</h4>
                    <br> 

        <form method="POST" >  
            {% csrf_token %}  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input class="btn btn-outline-primary" type="submit" name="submit" value="Sign Up"/></td>  
                </tr>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}
    

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>To-do List</title>
<meta name="viewport", content="width=device-width, initial-scale=1.0">
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Hi, {{ user }}</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todolist:show_todolist' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:logout_user' %}">Logout</a>
            </li>
          </ul>
        </div>
      </nav>

    <style>
        *{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }
        h1, h2, h5{
            text-align: center;
            color: #000000;
        }
        .grid-container{
            display: grid;
            grid-template-columns: auto auto auto auto;
            gap: 10px;
            padding: 10px;
        }
        body{
            background-image: url(https://cdn.dribbble.com/users/402090/screenshots/7972050/media/6dbbc85389e40707b39435357452fe27.gif);
        }
        .card:hover{
            background: rgb(227, 185, 255);
            border: 1px solid;
            color: white;
        }
        .row{
            display: flex;
            justify-content: center;
            align-items: flex-start;
            align-content: space-between;
        }   
        .btn1{
            border: none;
            outline: none;
            height: 40px;
            width: 10%;
            background-color: rgb(187, 212, 255);
            color: rgb(0, 0, 0);
            border-radius: 4px;
            font-weight: bold;
        }
        .btn1:hover{
            background: rgb(245, 249, 173);
            border: 1px solid;
            color: rgb(0, 0, 0);
        }
        .btn2{
            border: none;
            outline: none;
            height: 50px;
            width: 20%;
            background-color: rgb(255, 182, 253);
            color: rgb(0, 0, 0);
            border-radius: 4px;
            font-weight: bold;
        }
        .btn2:hover{
            background: rgb(255, 182, 253);
            border: 1px solid;
            color: rgb(255, 255, 255);
        }
        .btn3{
            border: none;
            outline: none;
            height: 50px;
            width: 20%;
            background-color: rgb(233, 255, 186);
            color: rgb(0, 0, 0);
            border-radius: 4px;
            font-weight: bold;
        }
        .btn3:hover{
            background: rgb(211, 211, 211);
            border: 1px solid;
            color: rgb(0, 0, 0);
        }
        .modal-header{
            background: rgb(235, 254, 255);
        }
        .modal-body{
            background: rgb(235, 254, 255);
        }
        .modal-footer{
            background: rgb(235, 254, 255);
        }
    </style>
{% endblock meta %}

{% block content%}
<br><h2>☆ {{ user }}'s To-do List ☆</h2><br>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
  $(document).ready(function(){
      $.get("/todolist/json", function(data) {
        console.log(data)
        for (i=0; i < data.length; i++){
          $(".row").append(`<div class="card" style="width: 18rem;">
            <div class="card text-center">
              <h5 class="card-title">${data[i].fields.title}</h5>
              <p class="card-text">${data[i].fields.date}</p>
              <p class="card-text">${data[i].fields.description}</p>
            </div></div>`)}});
      $("#create").click(function(){
      $.post("/todolist/add/", {
        title : $('#title').val(),
        description: $('#desc').val()},
        function (input){
          $(".row").append(`<div class="card" style="width: 18rem;">
            <div class="card text-center">
              <h5 class="card-title">${input.fields.title}</h5>
              <p class="card-text">${input.fields.date}</p>
              <p class="card-text">${input.fields.description}</p>
            </div></div>`)
      $('#title').val(''),
      $('#desc').val('')
        })})});
</script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <div style="text-align:center;">
    <button type="button" class="btn1 btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">+ New Task</button>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="modal-title fs-5" id="exampleModalLabel">New Task</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form>
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">Task</label>
                <input type="text" class="form-control" id="title">
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Description</label>
                <textarea class="form-control" id="desc"></textarea>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn2 btn-primary" id="create" data-bs-dismiss="modal">Create</button>
            <button type="button" class="btn3 btn-secondary" data-bs-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
    </div>

    <br><div class="row"></div><br>

    <h5>Last login session: {{last_login}}</h5>

 {% endblock content %}